name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # mainブランチにプッシュされたら自動起動

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # package-lock.jsonを元に厳密にインストール

      - name: Run Tests
        run: npm run test

      - name: Build
        env:
          # ★さっきGitHubに登録した暗号化キーを、ビルド時に環境変数として注入する魔法
          VITE_WARGAMING_APP_ID: ${{ secrets.VITE_WARGAMING_APP_ID }}
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4